### ISSUE TITLE
[12.0] salon_management - issue after installation still present

### ISSUE THREAD

**Issue by satriani-vai** [CybroOdoo/CybroAddons#115] opened 2019-04-29 09:11 UTC
https://github.com/CybroOdoo/CybroAddons/issues/113#issuecomment-487096568

**Comment by CybroOdoo** [comment] 2019-05-04 09:03
Hi,
We are not able to reproduce this issue. We have checked in fresh database as well as database consist of demo data.
Please make sure that you are using the updated version of Odoo 12.

**Closed as completed** 2019-05-13 05:25 UTC
